<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <!-- <material name = "green">
        <color rgba = "0 0.5 0 1"/>
    </material>
    <material name = "blue">
        <color rgba = "0 0 0.5 1"/>
    </material> -->

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_footprint"/>
    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz = "0 0 ${base_height}" rpy="0 0 0"/>
            <!-- <material name="green"/> -->

        </visual>
    </link>

    <link name = "second_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
    </link>

    <joint name="base_dummy_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${-base_height}" rpy="0 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <joint name="base_second_joint" type="continuous">
        <parent link="base_link"/>
        <child link="second_link"/>
        <origin xyz="${-base_length/4} ${base_width/2 + wheel_length/2} ${wheel_radius}" rpy="${pi/2}  0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>
    <link name = "Third_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>

            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
    </link>
    <joint name="base_third_joint" type="continuous">
        <parent link="base_link"/>
        <child link="Third_link"/>
        <origin xyz="${-base_length/4} ${-(base_width/2+wheel_length/2)} ${wheel_radius}" rpy="${pi/2} 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <link name="castor_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>

            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
    </link>

    <joint name="base_castor_joint" type="continuous">
        <parent link="base_link"/>
        <child link="castor_wheel"/>
        <origin xyz="${base_length/4} 0 ${wheel_radius/2}" rpy="0 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>
</robot>